## Wie zijn we?
Ons Meezingkoor Eindhoven is een voortzetting van het in 2009 opgerichte Brabant Meezingkoor Antares.
De oprichters van het Brabants Meezingkoor Antares hadden voor ogen een amusementskoor waar iedereen die van zingen houdt welkom is. Een laagdrempelig koor waarbij het plezier in zingen voorop stond. 
Doelstelling was ook om optredens te verzorgen in o.a. zorginstellingen. In de loop der jaren zijn er natuurlijk aanpassingen geweest, leden zijn gekomen en leden zijn gegaan. En ook het muziekale leidersschap is gewisseld. Na jarenlang succesvol onder leiding te hebben gestaan van Max Kruijzen is Wim van Ruijven, één van de oprichters van Antares, weer terug als koorleider. 
Ooit begonnen in de Zuidwester en later in .... heeft Ons Meezingkoor Eindhoven sinds enkele jaren als vaste repetitie ruimte het wijkcentrum 't Trefpunt in de Tempel. 

Schrijf hier in gewone tekst ongeveer twee of drie alinea's over het koor. Bijvoorbeeld hoe lang het koor bestaat, hoeveel leden er zijn en wat voor sfeer jullie belangrijk vinden.

Je kunt deze tekst gewoon vervangen. Je hoeft geen speciale opmaak te gebruiken.

## Wat zingen we graag?

Het repertoire  van Ons Meezingkoo Eindhoven bestaat al jaar en dag uit Nederlandstalige en internationale popsongs en evergreens. Liedjes die iedereen zich herinnert en kan meezingen.
Natuurlijk hebben we ook een reperoire voor de Kerstperiode én de Carnavalstijd.

Favourite nummers van ons koor zijn b.v.


Vertel hier iets meer over jullie repertoire. Je kunt ook een eenvoudig lijstje gebruiken:

- eerste voorbeeld;
- tweede voorbeeld;
- derde voorbeeld.

## Onze dirigent
Koorleider is Wim van Ruijven

